# Site
repository: LimDDung/LimDDung.github.io
# favicon: images/favicon.ico

# Personal info
name: ì„ê¸°í˜„
title: PHP ë°±ì—”ë“œ ê°œë°œì
email: ykh931104@naver.com
#website: ""

# Social links
# twitter_username: LimDDung
github_username:  LimDDung
# dribbble_username: jekyll
#facebook_username: LimDDung
# flickr_username: jekyll
# linkedin_username: LimDDung
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  ì•ˆë…•í•˜ì„¸ìš” PHP ë°±ì•¤ë“œ ê°œë°œì ì„ê¸°í˜„ ì…ë‹ˆë‹¤.<br>
  PHP & Python / JavaScript ê¸°ë°˜ì˜ 5ë…„ì°¨ ë°±ì—”ë“œ ê°œë°œìë¡œ ê°œì¸ì´ í•˜ê³  ì‹¶ì€ ì¼ ë³´ë‹¤ëŠ” íšŒì‚¬ì™€ íŒ€ì— ë„ì›€ì´ ë˜ëŠ” ê°œë°œìê°€ ë˜ê³ ì ì „ë¬¸ì„±ì„ ê°•í™”í•˜ê³  ì‚¬ëŒë“¤ì˜ ì‚¶ì— ë”ìš± í¸í•œ ì‚¶ì„ ì œê³µ í•˜ê¸° ìœ„í•´ ìµœì„ ì„ ë‹¤í•˜ëŠ” ì„ê¸°í˜„ì…ë‹ˆë‹¤.<br>
  ì•„ì§ ë°°ìš¸ ê²ƒì´ ë§ì§€ë§Œ, ê·¸ë§Œí¼ ë” ì„±ì¥í•  ìˆ˜ ìˆìŒì— ê°ì‚¬í•©ë‹ˆë‹¤.
  ğŸ‘ŠğŸ‘Š
# Projects Section
#projects_title: PROJECT

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs

  
# Footer
footer_show_references: true

# Build settings
#remote_theme: sproogen/resume-theme
remote_theme: LimDDung/LimDDung.github.io
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
