# Site
repository: LimDDung/LimDDung.github.io
# favicon: images/favicon.ico

# Personal info
name: ì„ê¸°í˜„
title: PHP ë°±ì—”ë“œ ê°œë°œì
email: ykh931104@naver.com
#website: ""

# Social links
# twitter_username: LimDDung
github_username:  LimDDung
# dribbble_username: jekyll
#facebook_username: LimDDung
# flickr_username: jekyll
# linkedin_username: LimDDung
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  ì•ˆë…•í•˜ì„¸ìš” PHP ë°±ì•¤ë“œ ê°œë°œì ì„ê¸°í˜„ ì…ë‹ˆë‹¤.

  ì›¹ ì„œë¹„ìŠ¤ ë°±ì—”ë“œ/í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œì— ìˆì–´ì„œ ë‹¤ì–‘í•œ ê²½í—˜ì´ ìˆìŠµë‹ˆë‹¤. Node.js, PHP, MySQL, Javascript , Jquery, Git ë“±ì„ ì‚¬ìš©í•˜ì—¬ í”„ë¡œë•ì…˜ ì„œë¹„ìŠ¤ë¥¼ ì„¤ê³„, ê°œë°œ, ìš´ì˜í•œ ê²½í—˜ìœ¼ë¡œ í™•ì¥ì„±ê³¼ ìœ ì§€ ë³´ìˆ˜ì„±ì´ ë†’ì€ ë°±ì—”ë“œ ì•„í‚¤í…ì²˜ì™€ íŒ¨í„´ì„ ìœ„í•´ ì–¸ì œë‚˜ ê³ ë¯¼í•˜ê³  ìˆìŠµë‹ˆë‹¤.

  ì˜¤í”ˆì†ŒìŠ¤ í”„ë¡œì íŠ¸ì— ê´€ì‹¬ì´ ë§ê³ , ë‹¤ì–‘í•œ ë°©ë²•ìœ¼ë¡œ ê¸°ì—¬ë¥¼ í•˜ë ¤ê³  ë…¸ë ¥í•˜ê³  ìˆìŠµë‹ˆë‹¤. ì–¸ì œë‚˜ ë°±ì—”ë“œ ê°œë°œì˜ ì •ìƒì— ë„ë‹¬ í•˜ê³  ì‹¶ë‹¤ê³  ìƒê° í•˜ë©° , í•­ìƒ ëª¨ë“  ìƒí™©ì—ì„œ ìµœì„ ì„ ë‹¤í•˜ê³  ìˆìŠµë‹ˆë‹¤.

  ë°±ì—”ë“œ ê°œë°œì´ë€ ê²°êµ­ ê°œë°œê³¼ ì†Œë¹„ìì™€ì˜ ì»¤ë®¤ë‹ˆì¼€ì´ì…˜ì´ ê°€ì¥ ì¤‘ìš”í•˜ë‹¤ê³  ìƒê°í•©ë‹ˆë‹¤. ì§„ì·¨ì ì¸ ì‚¬ê³ ë°©ì‹ê³¼ ì ê·¹ì ì¸ ë¬¸ì œí•´ê²° ëŠ¥ë ¥ìœ¼ë¡œ ë” ì¢‹ì€ ê°œë°œìë¡œ ì„±ì¥í•˜ê¸° ìœ„í•´ í•™ìŠµ! ë…¸ë ¥! ê²½í˜! ì„ ê²Œì„ë¦¬ í•˜ì§€ ì•Šê² ìŠµë‹ˆë‹¤.
  ğŸ‘ŠğŸ‘Š
# Projects Section
#projects_title: PROJECT

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs

  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
